### ISSUE TITLE
Is it possible to ssh into and control an instance?

### ISSUE THREAD

**Issue by Drwhit** [cloudyr/aws.ec2#22] opened 2017-01-25 21:14 UTC
Great work on this project, I have been looking for something like this. 

The example shows how to start up an instance with Rstudio server, which I believe would be controlled from a web browser?

With this package, is it possible to use R to start up R on the AWS instance, and continue to send it commands?  I believe this would have to be done through SSH.

**Comment by leeper** [comment] 2017-07-06 20:14
Duplicate of #14.

**Closed by leeper** 2017-07-06 20:14 UTC
Labels: duplicate, question
